// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VieITStore.Models;

#nullable disable

namespace VieITStore.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260814164313_AddColorAndDiscountCode")]
    partial class AddColorAndDiscountCode
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VieITStore.Models.Entities.ChiTietDieuChinhTonKho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PhieuDieuChinhTonKhoId")
                        .HasColumnType("int");

                    b.Property<int>("SanPhamId")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongSau")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongThayDoi")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongTruoc")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PhieuDieuChinhTonKhoId");

                    b.HasIndex("SanPhamId");

                    b.ToTable("ChiTietDieuChinhTonKhos");
                });

            modelBuilder.Entity("VieITStore.Models.Entities.ChiTietDonHang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DonHangId")
                        .HasColumnType("int");

                    b.Property<int>("SanPhamId")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DonHangId");

                    b.HasIndex("SanPhamId");

                    b.ToTable("ChiTietDonHangs");
                });

            modelBuilder.Entity("VieITStore.Models.Entities.ChiTietHoaDon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("HoaDonId")
                        .HasColumnType("int");

                    b.Property<int>("SanPhamId")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HoaDonId");

                    b.HasIndex("SanPhamId");

                    b.ToTable("ChiTietHoaDons");
                });

            modelBuilder.Entity("VieITStore.Models.Entities.ChiTietPhieuNhap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DonGiaNhap")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PhieuNhapId")
                        .HasColumnType("int");

                    b.Property<int>("SanPhamId")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PhieuNhapId");

                    b.HasIndex("SanPhamId");

                    b.ToTable("ChiTietPhieuNhaps");
                });

            modelBuilder.Entity("VieITStore.Models.Entities.DanhGia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("HienThi")
                        .HasColumnType("bit");

                    b.Property<int>("KhachHangId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayDanhGia")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("SanPhamId")
                        .HasColumnType("int");

                    b.Property<int>("SoSao")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SanPhamId");

                    b.HasIndex("KhachHangId", "SanPhamId")
                        .IsUnique();

                    b.ToTable("DanhGias");
                });

            modelBuilder.Entity("VieITStore.Models.Entities.DanhMuc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("HienThi")
                        .HasColumnType("bit");

                    b.Property<int?>("MaGiamGiaId")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ThuTu")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaGiamGiaId");

                    b.ToTable("DanhMucs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HienThi = true,
                            TenDanhMuc = "Linh kiện điện tử",
                            ThuTu = 1
                        },
                        new
                        {
                            Id = 2,
                            HienThi = true,
                            TenDanhMuc = "Phụ kiện điện thoại",
                            ThuTu = 2
                        },
                        new
                        {
                            Id = 3,
                            HienThi = true,
                            TenDanhMuc = "Phụ kiện máy tính",
                            ThuTu = 3
                        },
                        new
                        {
                            Id = 4,
                            HienThi = true,
                            TenDanhMuc = "Thiết bị điện tử",
                            ThuTu = 4
                        });
                });

            modelBuilder.Entity("VieITStore.Models.Entities.DiaChiGiaoHang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DiaChiChiTiet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTenNguoiNhan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KhachHangId")
                        .HasColumnType("int");

                    b.Property<bool>("LaMacDinh")
                        .HasColumnType("bit");

                    b.Property<string>("PhuongXa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuanHuyen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TinhThanh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KhachHangId");

                    b.ToTable("DiaChiGiaoHangs");
                });

            modelBuilder.Entity("VieITStore.Models.Entities.DonHang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("DaThanhToan")
                        .HasColumnType("bit");

                    b.Property<string>("DiaChiGiaoHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("GiamGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("HinhThucNhanHang")
                        .HasColumnType("int");

                    b.Property<string>("HoTenNguoiNhan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KenhBan")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("KhachHangId")
                        .HasColumnType("int");

                    b.Property<string>("LyDoHuy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaDonHang")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime?>("NgayCapNhatTrangThai")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayDat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayGiaoDuKien")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayGiaoThucTe")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayThanhToan")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiCapNhatTrangThaiId")
                        .HasColumnType("int");

                    b.Property<int?>("NhanVienXuLyId")
                        .HasColumnType("int");

                    b.Property<decimal>("PhiVanChuyen")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PhuongThucThanhToan")
                        .HasColumnType("int");

                    b.Property<string>("SoDienThoaiNguoiNhan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TongThanhToan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TongTienHang")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KhachHangId");

                    b.HasIndex("MaDonHang")
                        .IsUnique();

                    b.HasIndex("NguoiCapNhatTrangThaiId");

                    b.HasIndex("NhanVienXuLyId");

                    b.ToTable("DonHangs");
                });

            modelBuilder.Entity("VieITStore.Models.Entities.GioHang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<int>("SanPhamId")
                        .HasColumnType("int");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SanPhamId");

                    b.HasIndex("NguoiDungId", "SanPhamId")
                        .IsUnique()
                        .HasFilter("[NguoiDungId] IS NOT NULL");

                    b.HasIndex("SessionId", "SanPhamId")
                        .IsUnique()
                        .HasFilter("[SessionId] IS NOT NULL");

                    b.ToTable("GioHangs", t =>
                        {
                            t.HasCheckConstraint("CK_GioHangs_Owner", "([NguoiDungId] IS NOT NULL AND [SessionId] IS NULL) OR ([NguoiDungId] IS NULL AND [SessionId] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("VieITStore.Models.Entities.HoaDon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DonHangId")
                        .HasColumnType("int");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("GiamGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("KhachHangId")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiLap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhuongThucThanhToan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoHoaDon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ThueVAT")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("TienThueVAT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TongThanhToan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TongTienHang")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DonHangId")
                        .IsUnique()
                        .HasFilter("[DonHangId] IS NOT NULL");

                    b.HasIndex("KhachHangId");

                    b.HasIndex("SoHoaDon")
                        .IsUnique();

                    b.ToTable("HoaDons");
                });

            modelBuilder.Entity("VieITStore.Models.Entities.KhachHang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GioiTinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaSoThue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<string>("TenCongTy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NguoiDungId")
                        .IsUnique();

                    b.ToTable("KhachHangs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GioiTinh = "Nam",
                            NgaySinh = new DateTime(1990, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungId = 3
                        });
                });

            modelBuilder.Entity("VieITStore.Models.Entities.MaGiamGia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("ApDungToanBo")
                        .HasColumnType("bit");

                    b.Property<int?>("DanhMucId")
                        .HasColumnType("int");

                    b.Property<decimal?>("GiaGiamToiDa")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("GiaToiThieu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MaCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PhanTramGiam")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("SoLanDaSuDung")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuongSuDung")
                        .HasColumnType("int");

                    b.Property<string>("TenKhuyenMai")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DanhMucId");

                    b.ToTable("MaGiamGias");
                });

            modelBuilder.Entity("VieITStore.Models.Entities.Mau", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MaMau")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenMau")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Maus");
                });

            modelBuilder.Entity("VieITStore.Models.Entities.NguoiDung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LanDangNhapCuoi")
                        .HasColumnType("datetime2");

                    b.Property<string>("MatKhauHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<int>("VaiTro")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("NguoiDungs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@vieitstore.com",
                            HoTen = "Quản trị viên",
                            MatKhauHash = "$2a$11$JyJ7cHu9cnJSM4k/dtsifORQDaZSUWn7cuFHCeeOu4pjezwpUarqm",
                            NgayTao = new DateTime(2026, 8, 6, 19, 43, 59, 742, DateTimeKind.Local).AddTicks(1862),
                            TenDangNhap = "admin",
                            TrangThai = true,
                            VaiTro = 1
                        },
                        new
                        {
                            Id = 2,
                            Email = "nhanvien@vieitstore.com",
                            HoTen = "Nhân viên bán hàng",
                            MatKhauHash = "$2a$11$BC0g0F3PFYN0.wmPKGVH2eZyOT.K6tkmPZFTScnWbsqJOPl9../3y",
                            NgayTao = new DateTime(2026, 8, 6, 19, 43, 59, 742, DateTimeKind.Local).AddTicks(2507),
                            TenDangNhap = "nhanvien",
                            TrangThai = true,
                            VaiTro = 2
                        },
                        new
                        {
                            Id = 3,
                            Email = "khachhang@vieitstore.com",
                            HoTen = "Nguyễn Văn A",
                            MatKhauHash = "$2a$11$ub58BEpDCXROdMsUtf7nnui5Xj91n63eWJ16pDIvnKM2pIBdql2Mi",
                            NgayTao = new DateTime(2026, 8, 6, 19, 43, 59, 742, DateTimeKind.Local).AddTicks(2510),
                            TenDangNhap = "khachhang",
                            TrangThai = true,
                            VaiTro = 3
                        });
                });

            modelBuilder.Entity("VieITStore.Models.Entities.NhaCungCap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaNCC")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaSoThue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiLienHe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNCC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("MaNCC")
                        .IsUnique();

                    b.ToTable("NhaCungCaps");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DiaChi = "Quận 1, TP.HCM",
                            MaNCC = "NCC001",
                            NguoiLienHe = "Nguyễn Văn A",
                            SoDienThoai = "0909123456",
                            TenNCC = "Công ty TNHH Điện tử ABC",
                            TrangThai = true
                        },
                        new
                        {
                            Id = 2,
                            DiaChi = "Quận 3, TP.HCM",
                            MaNCC = "NCC002",
                            NguoiLienHe = "Trần Thị B",
                            SoDienThoai = "0912345678",
                            TenNCC = "Phân phối Linh kiện XYZ",
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("VieITStore.Models.Entities.PhieuDieuChinhTonKho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LoaiGiaoDich")
                        .HasColumnType("int");

                    b.Property<string>("LyDo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MaPhieu")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiThucHienId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaPhieu")
                        .IsUnique();

                    b.HasIndex("NguoiThucHienId");

                    b.ToTable("PhieuDieuChinhTonKhos");
                });

            modelBuilder.Entity("VieITStore.Models.Entities.PhieuNhap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaPhieuNhap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayNhap")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiNhapId")
                        .HasColumnType("int");

                    b.Property<int>("NhaCungCapId")
                        .HasColumnType("int");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("NguoiNhapId");

                    b.HasIndex("NhaCungCapId");

                    b.ToTable("PhieuNhaps");
                });

            modelBuilder.Entity("VieITStore.Models.Entities.SanPham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BaoHanh")
                        .HasColumnType("int");

                    b.Property<int>("DanhMucId")
                        .HasColumnType("int");

                    b.Property<string>("DonViTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("GiaBan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("GiaKhuyenMai")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GiaNhap")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhAnhBoSung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaVach")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MauId")
                        .HasColumnType("int");

                    b.Property<string>("MoTaChiTiet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTaNgan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<bool>("NoiBat")
                        .HasColumnType("bit");

                    b.Property<string>("Slug")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoLuongDaBan")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongTon")
                        .HasColumnType("int");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThongSoKyThuat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThuongHieu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<string>("XuatXu")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DanhMucId");

                    b.HasIndex("MaSanPham")
                        .IsUnique();

                    b.HasIndex("MaVach")
                        .IsUnique()
                        .HasFilter("[MaVach] IS NOT NULL");

                    b.HasIndex("MauId");

                    b.ToTable("SanPhams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaoHanh = 0,
                            DanhMucId = 1,
                            DonViTinh = "Cái",
                            GiaBan = 3990000m,
                            GiaKhuyenMai = 3590000m,
                            GiaNhap = 2500000m,
                            HinhAnh = "/images/cpu-i5.jpg",
                            MaSanPham = "CPU001",
                            MoTaNgan = "Bộ xử lý Intel Core i5 generasi 12",
                            NgayCapNhat = new DateTime(2026, 8, 6, 19, 43, 59, 743, DateTimeKind.Local).AddTicks(5983),
                            NgayTao = new DateTime(2026, 8, 6, 19, 43, 59, 743, DateTimeKind.Local).AddTicks(5978),
                            NoiBat = true,
                            SoLuongDaBan = 10,
                            SoLuongTon = 50,
                            TenSanPham = "CPU Intel Core i5-12400F",
                            TrangThai = true
                        },
                        new
                        {
                            Id = 2,
                            BaoHanh = 0,
                            DanhMucId = 1,
                            DonViTinh = "Cái",
                            GiaBan = 7990000m,
                            GiaKhuyenMai = 7490000m,
                            GiaNhap = 5000000m,
                            HinhAnh = "/images/gpu-rtx3060.jpg",
                            MaSanPham = "GPU001",
                            MoTaNgan = "Card đồ họa NVIDIA RTX 3060 12GB GDDR6",
                            NgayCapNhat = new DateTime(2026, 8, 6, 19, 43, 59, 744, DateTimeKind.Local).AddTicks(3899),
                            NgayTao = new DateTime(2026, 8, 6, 19, 43, 59, 744, DateTimeKind.Local).AddTicks(3896),
                            NoiBat = true,
                            SoLuongDaBan = 5,
                            SoLuongTon = 30,
                            TenSanPham = "VGA ASUS RTX 3060 12GB",
                            TrangThai = true
                        },
                        new
                        {
                            Id = 3,
                            BaoHanh = 0,
                            DanhMucId = 1,
                            DonViTinh = "Cái",
                            GiaBan = 990000m,
                            GiaKhuyenMai = 890000m,
                            GiaNhap = 600000m,
                            HinhAnh = "/images/ssd-samsung.jpg",
                            MaSanPham = "SSD001",
                            MoTaNgan = "Ổ cứng NVMe tốc độ cao 500GB",
                            NgayCapNhat = new DateTime(2026, 8, 6, 19, 43, 59, 744, DateTimeKind.Local).AddTicks(3908),
                            NgayTao = new DateTime(2026, 8, 6, 19, 43, 59, 744, DateTimeKind.Local).AddTicks(3908),
                            NoiBat = true,
                            SoLuongDaBan = 25,
                            SoLuongTon = 100,
                            TenSanPham = "SSD Samsung 980 NVMe 500GB",
                            TrangThai = true
                        },
                        new
                        {
                            Id = 4,
                            BaoHanh = 0,
                            DanhMucId = 2,
                            DonViTinh = "Cái",
                            GiaBan = 150000m,
                            GiaKhuyenMai = 129000m,
                            GiaNhap = 80000m,
                            HinhAnh = "/images/cable-typec.jpg",
                            MaSanPham = "ACC001",
                            MoTaNgan = "Cáp sạc nhanh Type-C to Lightning chất lượng cao",
                            NgayCapNhat = new DateTime(2026, 8, 6, 19, 43, 59, 744, DateTimeKind.Local).AddTicks(3913),
                            NgayTao = new DateTime(2026, 8, 6, 19, 43, 59, 744, DateTimeKind.Local).AddTicks(3913),
                            NoiBat = false,
                            SoLuongDaBan = 60,
                            SoLuongTon = 200,
                            TenSanPham = "Cáp sạc nhanh Type-C to Lightning 20W",
                            TrangThai = true
                        },
                        new
                        {
                            Id = 5,
                            BaoHanh = 0,
                            DanhMucId = 3,
                            DonViTinh = "Cái",
                            GiaBan = 899000m,
                            GiaNhap = 600000m,
                            HinhAnh = "/images/mouse-logitech.jpg",
                            MaSanPham = "ACC002",
                            MoTaNgan = "Chuột gaming Logitech G502 HERO chuyên nghiệp",
                            NgayCapNhat = new DateTime(2026, 8, 6, 19, 43, 59, 744, DateTimeKind.Local).AddTicks(3919),
                            NgayTao = new DateTime(2026, 8, 6, 19, 43, 59, 744, DateTimeKind.Local).AddTicks(3918),
                            NoiBat = false,
                            SoLuongDaBan = 15,
                            SoLuongTon = 45,
                            TenSanPham = "Chuột Logitech G502 HERO",
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("VieITStore.Models.Entities.SerialSanPham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChiTietDonHangId")
                        .HasColumnType("int");

                    b.Property<int?>("ChiTietPhieuNhapId")
                        .HasColumnType("int");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MaSerial")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("NgayBatDauBaoHanh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayHetHanBaoHanh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("SanPhamId")
                        .HasColumnType("int");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChiTietDonHangId");

                    b.HasIndex("ChiTietPhieuNhapId");

                    b.HasIndex("MaSerial")
                        .IsUnique();

                    b.HasIndex("SanPhamId");

                    b.ToTable("SerialSanPhams");
                });

            modelBuilder.Entity("VieITStore.Models.Entities.ChiTietDieuChinhTonKho", b =>
                {
                    b.HasOne("VieITStore.Models.Entities.PhieuDieuChinhTonKho", "PhieuDieuChinhTonKho")
                        .WithMany("ChiTiets")
                        .HasForeignKey("PhieuDieuChinhTonKhoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VieITStore.Models.Entities.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("SanPhamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PhieuDieuChinhTonKho");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("VieITStore.Models.Entities.ChiTietDonHang", b =>
                {
                    b.HasOne("VieITStore.Models.Entities.DonHang", "DonHang")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("DonHangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VieITStore.Models.Entities.SanPham", "SanPham")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("SanPhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonHang");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("VieITStore.Models.Entities.ChiTietHoaDon", b =>
                {
                    b.HasOne("VieITStore.Models.Entities.HoaDon", "HoaDon")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("HoaDonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VieITStore.Models.Entities.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("SanPhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDon");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("VieITStore.Models.Entities.ChiTietPhieuNhap", b =>
                {
                    b.HasOne("VieITStore.Models.Entities.PhieuNhap", "PhieuNhap")
                        .WithMany("ChiTietPhieuNhaps")
                        .HasForeignKey("PhieuNhapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VieITStore.Models.Entities.SanPham", "SanPham")
                        .WithMany("ChiTietPhieuNhaps")
                        .HasForeignKey("SanPhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhieuNhap");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("VieITStore.Models.Entities.DanhGia", b =>
                {
                    b.HasOne("VieITStore.Models.Entities.KhachHang", "KhachHang")
                        .WithMany("DanhGias")
                        .HasForeignKey("KhachHangId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VieITStore.Models.Entities.SanPham", "SanPham")
                        .WithMany("DanhGias")
                        .HasForeignKey("SanPhamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("VieITStore.Models.Entities.DanhMuc", b =>
                {
                    b.HasOne("VieITStore.Models.Entities.MaGiamGia", null)
                        .WithMany("DanhMucs")
                        .HasForeignKey("MaGiamGiaId");
                });

            modelBuilder.Entity("VieITStore.Models.Entities.DiaChiGiaoHang", b =>
                {
                    b.HasOne("VieITStore.Models.Entities.KhachHang", "KhachHang")
                        .WithMany("DiaChiGiaoHangs")
                        .HasForeignKey("KhachHangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("VieITStore.Models.Entities.DonHang", b =>
                {
                    b.HasOne("VieITStore.Models.Entities.KhachHang", "KhachHang")
                        .WithMany("DonHangs")
                        .HasForeignKey("KhachHangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VieITStore.Models.Entities.NguoiDung", "NguoiCapNhatTrangThai")
                        .WithMany()
                        .HasForeignKey("NguoiCapNhatTrangThaiId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VieITStore.Models.Entities.NguoiDung", "NhanVienXuLy")
                        .WithMany()
                        .HasForeignKey("NhanVienXuLyId");

                    b.Navigation("KhachHang");

                    b.Navigation("NguoiCapNhatTrangThai");

                    b.Navigation("NhanVienXuLy");
                });

            modelBuilder.Entity("VieITStore.Models.Entities.GioHang", b =>
                {
                    b.HasOne("VieITStore.Models.Entities.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VieITStore.Models.Entities.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("SanPhamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NguoiDung");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("VieITStore.Models.Entities.HoaDon", b =>
                {
                    b.HasOne("VieITStore.Models.Entities.DonHang", "DonHang")
                        .WithOne("HoaDon")
                        .HasForeignKey("VieITStore.Models.Entities.HoaDon", "DonHangId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VieITStore.Models.Entities.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("KhachHangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonHang");

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("VieITStore.Models.Entities.KhachHang", b =>
                {
                    b.HasOne("VieITStore.Models.Entities.NguoiDung", "NguoiDung")
                        .WithOne("KhachHang")
                        .HasForeignKey("VieITStore.Models.Entities.KhachHang", "NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("VieITStore.Models.Entities.MaGiamGia", b =>
                {
                    b.HasOne("VieITStore.Models.Entities.DanhMuc", "DanhMuc")
                        .WithMany()
                        .HasForeignKey("DanhMucId");

                    b.Navigation("DanhMuc");
                });

            modelBuilder.Entity("VieITStore.Models.Entities.PhieuDieuChinhTonKho", b =>
                {
                    b.HasOne("VieITStore.Models.Entities.NguoiDung", "NguoiThucHien")
                        .WithMany()
                        .HasForeignKey("NguoiThucHienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NguoiThucHien");
                });

            modelBuilder.Entity("VieITStore.Models.Entities.PhieuNhap", b =>
                {
                    b.HasOne("VieITStore.Models.Entities.NguoiDung", "NguoiNhap")
                        .WithMany()
                        .HasForeignKey("NguoiNhapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VieITStore.Models.Entities.NhaCungCap", "NhaCungCap")
                        .WithMany()
                        .HasForeignKey("NhaCungCapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiNhap");

                    b.Navigation("NhaCungCap");
                });

            modelBuilder.Entity("VieITStore.Models.Entities.SanPham", b =>
                {
                    b.HasOne("VieITStore.Models.Entities.DanhMuc", "DanhMuc")
                        .WithMany("SanPhams")
                        .HasForeignKey("DanhMucId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VieITStore.Models.Entities.Mau", "Mau")
                        .WithMany("SanPhams")
                        .HasForeignKey("MauId");

                    b.Navigation("DanhMuc");

                    b.Navigation("Mau");
                });

            modelBuilder.Entity("VieITStore.Models.Entities.SerialSanPham", b =>
                {
                    b.HasOne("VieITStore.Models.Entities.ChiTietDonHang", "ChiTietDonHang")
                        .WithMany("SerialSanPhams")
                        .HasForeignKey("ChiTietDonHangId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VieITStore.Models.Entities.ChiTietPhieuNhap", "ChiTietPhieuNhap")
                        .WithMany("SerialSanPhams")
                        .HasForeignKey("ChiTietPhieuNhapId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VieITStore.Models.Entities.SanPham", "SanPham")
                        .WithMany("SerialSanPhams")
                        .HasForeignKey("SanPhamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChiTietDonHang");

                    b.Navigation("ChiTietPhieuNhap");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("VieITStore.Models.Entities.ChiTietDonHang", b =>
                {
                    b.Navigation("SerialSanPhams");
                });

            modelBuilder.Entity("VieITStore.Models.Entities.ChiTietPhieuNhap", b =>
                {
                    b.Navigation("SerialSanPhams");
                });

            modelBuilder.Entity("VieITStore.Models.Entities.DanhMuc", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("VieITStore.Models.Entities.DonHang", b =>
                {
                    b.Navigation("ChiTietDonHangs");

                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("VieITStore.Models.Entities.HoaDon", b =>
                {
                    b.Navigation("ChiTietHoaDons");
                });

            modelBuilder.Entity("VieITStore.Models.Entities.KhachHang", b =>
                {
                    b.Navigation("DanhGias");

                    b.Navigation("DiaChiGiaoHangs");

                    b.Navigation("DonHangs");
                });

            modelBuilder.Entity("VieITStore.Models.Entities.MaGiamGia", b =>
                {
                    b.Navigation("DanhMucs");
                });

            modelBuilder.Entity("VieITStore.Models.Entities.Mau", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("VieITStore.Models.Entities.NguoiDung", b =>
                {
                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("VieITStore.Models.Entities.PhieuDieuChinhTonKho", b =>
                {
                    b.Navigation("ChiTiets");
                });

            modelBuilder.Entity("VieITStore.Models.Entities.PhieuNhap", b =>
                {
                    b.Navigation("ChiTietPhieuNhaps");
                });

            modelBuilder.Entity("VieITStore.Models.Entities.SanPham", b =>
                {
                    b.Navigation("ChiTietDonHangs");

                    b.Navigation("ChiTietPhieuNhaps");

                    b.Navigation("DanhGias");

                    b.Navigation("SerialSanPhams");
                });
#pragma warning restore 612, 618
        }
    }
}
